/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as QuickScanRouteImport } from './routes/quick-scan'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ClaimIdRouteImport } from './routes/claim.$id'
import { Route as ItemIdRouteImport } from './routes/item.$id'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickScanRoute = QuickScanRouteImport.update({
  id: '/quick-scan',
  path: '/quick-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimIdRoute = ClaimIdRouteImport.update({
  id: '/claim/$id',
  path: '/claim/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemIdRoute = ItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProfileRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/quick-scan': typeof QuickScanRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/claim/$id': typeof ClaimIdRoute
  '/item/$id': typeof ItemIdRoute
  '/profile/$id': typeof ProfileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/quick-scan': typeof QuickScanRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/claim/$id': typeof ClaimIdRoute
  '/item/$id': typeof ItemIdRoute
  '/profile/$id': typeof ProfileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/quick-scan': typeof QuickScanRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/claim/$id': typeof ClaimIdRoute
  '/item/$id': typeof ItemIdRoute
  '/profile/$id': typeof ProfileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/discover'
    | '/feed'
    | '/login'
    | '/matches'
    | '/notifications'
    | '/profile'
    | '/quick-scan'
    | '/register'
    | '/report'
    | '/scan'
    | '/settings'
    | '/claim/$id'
    | '/item/$id'
    | '/profile/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/discover'
    | '/feed'
    | '/login'
    | '/matches'
    | '/notifications'
    | '/profile'
    | '/quick-scan'
    | '/register'
    | '/report'
    | '/scan'
    | '/settings'
    | '/claim/$id'
    | '/item/$id'
    | '/profile/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/discover'
    | '/feed'
    | '/login'
    | '/matches'
    | '/notifications'
    | '/profile'
    | '/quick-scan'
    | '/register'
    | '/report'
    | '/scan'
    | '/settings'
    | '/claim/$id'
    | '/item/$id'
    | '/profile/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  MatchesRoute: typeof MatchesRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  QuickScanRoute: typeof QuickScanRoute
  RegisterRoute: typeof RegisterRoute
  ReportRoute: typeof ReportRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  ClaimIdRoute: typeof ClaimIdRoute
  ItemIdRoute: typeof ItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-scan': {
      id: '/quick-scan'
      path: '/quick-scan'
      fullPath: '/quick-scan'
      preLoaderRoute: typeof QuickScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$id': {
      id: '/claim/$id'
      path: '/claim/$id'
      fullPath: '/claim/$id'
      preLoaderRoute: typeof ClaimIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$id': {
      id: '/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof ItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof ProfileRoute
    }
  }
}

interface ProfileRouteChildren {
  ProfileIdRoute: typeof ProfileIdRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileIdRoute: ProfileIdRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  MatchesRoute: MatchesRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRouteWithChildren,
  QuickScanRoute: QuickScanRoute,
  RegisterRoute: RegisterRoute,
  ReportRoute: ReportRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  ClaimIdRoute: ClaimIdRoute,
  ItemIdRoute: ItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
